site_name: bert-vits2 合成效果对比 vits

nav:
  - Home: index.md
  # 添加您的其他页面...

theme:
  name: material
  features:
    - content.tabs  # 添加此行来启用标签页功能
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/git-alt
    repo_url: https://github.com/lunar333/vits-japanese-finetune.git

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lunar333/vits-japanese-finetune.git
